spring:
  profiles:
    active: dev
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        metadata:
          broker:
            list: 127.0.0.1:9092
        message:
          send:
            max:
              retries: 3
        linger:
          ms: 1


  datasource:
    url: jdbc:postgresql://192.168.99.100/matrix
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  resources:
    static-locations: classpath:/templates/
  redis:
    host: localhost
    port: 6379
    database: 0

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

matrix:
  secretKey: dGVzdA==
  OSSUrl: http://192.168.99.100:9001
  OSSSecretKey: minio123
  OSSAccessKey: minio
  ImagePathBase: http://192.168.99.100:9001/matrix/

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8888
