spring:
  profiles:
    active: prod
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    producer:
      bootstrap-servers: ${kafka_server:127.0.0.1:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        metadata:
          broker:
            list: ${kafka_server:127.0.0.1:9092}
        message:
          send:
            max:
              retries: 3
        linger:
          ms: 1


  datasource:
    url: jdbc:${postgre_url:postgresql://127.0.0.1/matrix}
    username: ${postgre_username:postgres}
    password: ${postgre_password:test}
    driver-class-name: org.postgresql.Driver
  resources:
    static-locations: classpath:/templates/
  redis:
    host: ${redis_url:localhost}
    port: 6379
    database: 0

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

matrix:
  secretKey: ${secret_key:dGVzdA==}
  OSSUrl: ${oss_url:http://127.0.0.1:9001}
  OSSSecretKey: ${oss_secret_key:minio123}
  OSSAccessKey: ${oss_access_key:minio}
  ImagePathBase: ${image_path_base:http://127.0.0.1:9001/matrix/}
  UrlBase: ${url_base:http://127.0.0.1:8888/}

server:
  tomcat:
    uri-encoding: UTF-8
  port: ${port:8888}
