spring:
  profiles:
    active: dev
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:postgresql://127.0.0.1/matrix
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  resources:
    static-locations: classpath:/templates/
  redis:
    host: localhost
    port: 6379
    database: 0

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

matrix:
  secretKey: dGVzdA==
  OSSUrl: http://127.0.0.1:9001
  OSSSecretKey: minio123
  OSSAccessKey: minio
  ImagePathBase: http://127.0.0.1:9001/matrix/

rocketmq:
  isOnOff: on
#发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
  groupName: cyprinus
  #mq的nameserver地址
  namesrvAddr: localhost:9876
  #消息最大长度 默认1024*4(4M)
  maxMessageSize: 4096
  #发送消息超时时间,默认3000
  sendMsgTimeout: 3000
  #发送消息失败重试次数，默认2
  retryTimesWhenSendFailed: 2

  name-server: ip:9876
  producer:
    group: my-group

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8888
