spring:
  profiles:
    active: dev
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:postgresql://127.0.0.1/matrix
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  resources:
    static-locations: classpath:/templates/
  redis:
    host: localhost
    port: 6379
    database: 0

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8888
